Update style.css file and README.md file
Jeanbulambo/Leaderboard pull request #3
Opened 2022-07-29 23:42 UTC by Jeanbulambo

In this PR, we Add style to the Leaderboard and Update REAM.md file project

2022-07-29 23:56 UTC, Rustamxon7 requested changes
Hi @Jeanbulambo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 23:56 UTC, Rustamxon7 commented on README.md
> +[Live Demo Link](https://jeanbulambo.github.io/Leaderboard/)
Kindly add a screenshot to your Readme file.

2022-07-29 23:56 UTC, Rustamxon7 commented on README.md
> -[Live Demo Link](link here)
It looks like you forgot to add the MIT license to your project. Kindly fix this issue as well.

2022-07-30 09:43 UTC, KDlamini approved these changes
### Hi  @Jeanbulambo  🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!🎊 🥳 

## Highlights 🌞 
✔️  Styling implemented correctly
✔️  No linter errors

# Status: Approved ✔️ 

![giphyapproved](https://user-images.githubusercontent.com/38088818/152676874-3b2edc2c-a46f-4da6-b253-be859d2a2c65.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 11:30 UTC, merged